export const eventos = [
  { id: 1, 
    nome: 'Festival Luzes da Cidade', 
    data: '12/10/2026 - 20:00', 
    local: 'Arena Central', 
    organizador: 'Eventos Brasil', 
    fornecedor: 'Palco & Som',
    status: 'aprovado' 
  },
  { id: 2, 
    nome: 'Show Horizonte', 
    data: '18/10/2026 - 19:30', 
    local: 'Teatro Aurora', 
    organizador: 'Viva Cultura', 
    fornecedor: 'Música Viva',
    status: 'reprovado'  
  },
  { id: 3, 
    nome: 'Semana do Rock', 
    data: '25/10/2026 - 21:00', 
    local: 'Parque Municipal', 
    organizador: 'Rock Produções', 
    fornecedor: 'Luzes Pro',
    status: 'aprovado'  
  },
  { id: 4, 
    nome: 'Feira Criativa', 
    data: '02/11/2026 - 10:00', 
    local: 'Centro de Eventos', 
    organizador: 'Ideia Livre', 
    fornecedor: 'Expo Estruturas',
    status: 'reprovado'  
  },
  { id: 5, 
    nome: 'Noite Eletrônica', 
    data: '08/11/2026 - 22:00', 
    local: 'Clube Pulse', 
    organizador: 'Wave Eventos', 
    fornecedor: 'Sound Lab',
    status: 'reprovado'  
  },
  { id: 6, 
    nome: 'Festival de Verão', 
    data: '15/11/2026 - 16:00', 
    local: 'Praia Central', 
    organizador: 'Sol Produções', 
    fornecedor: 'Mega Palco',
    status: 'aprovado'  
  },
]
